name: NameRE
version: '0.0.1-ALPHA'
main: com.github.white555gamer.namere.NameRE
api-version: 1.19
authors: [ WHITE555Gamer ]
description: Minecraft's mini-plugin for easier name edit or redirect.
website: https://www.curseforge.com/minecraft/bukkit-plugins/namere

commands:
  NameRE:
    usage: /NameRE < edit | reset >-< all | custom | display | list> <PlayerName> <AfterName>
    description: You can edit or reset player name.